@extends('index',['setting' => $setting])

@section('content')

<div class="fh5co-hero" style="height: 250px">
    <div class="fh5co-overlay" style="background-color:rgba(0, 66, 150, 0.71);"></div>
    <div class="fh5co-cover text-center header-a" data-stellar-background-ratio="0.5" style="background-image: url({{asset('images/header/batik.png')}});">
        <div class="desc animate-box" style="top: 180px">
            <h2>Cek Pemesanan</h2>
        </div>
    </div>
</div>
<!-- end:header-top -->
<div id="fh5co-work-section">
    <div class="container">
        <div class="row">
            <div class="col-md-12 heading-section">
                <h3>Syarat dan Ketentuan</h3>
                <p><span>SYARAT PENGGUNAAN DI BAWAH INI HARUS DIBACA SEBELUM MENGGUNAKAN SITUS INI. PENGGUNAAN SITUS INI MENUNJUKKAN PENERIMAAN DAN KEPATUHAN TERHADAP SYARAT DAN KETENTUAN DI BAWAH INI.</span></p>

                <p><span>Airy.com</span><span> situs ("Situs") dikelola oleh Airy ("kami"). Dengan mengakses dan/atau menggunakan Situs, Anda mengakui bahwa Anda telah membaca dan memahami, dan menyetujui untuk terikat oleh Syarat Penggunaan yang ditetapkan di bawah ini dan syarat dan ketentuan lainnya dalam kaitannya dengan Situs, termasuk namun tidak terbatas pada kerahasiaan dan FAQ, yang merupakan bagian yang tidak terpisahkan dari Syarat Penggunaan ("Syarat"). Anda harus setidaknya berusia delapan belas (18) tahun untuk menggunakan Situs ini.</span></p>

                <p><span>Harap diketahui bahwa kami dapat mengubah, memodifikasi, menambah dan menghapus Syarat ini sewaktu-waktu tanpa pemberitahuan sebelumnya. Syarat harus dibaca secara berkala. Dengan terus menggunakan Situs ini setelah perubahan tersebut terhadap Syarat, pengunjung, pengguna atau Pengguna Terdaftar ("Anda" atau "pengguna") sepakat dan menyetujui perubahan. Jika Anda menggunakan salah satu layanan kami yang lain, maka penggunaan Anda didasarkan pada kepatuhan dan penerimaan terhadap syarat dan ketentuan yang berlaku untuk layanan tersebut.</span></p>

                <h4><span>LINGKUP LAYANAN KAMI</span></h4>
                <ol>
                    <li><span>Melalui Situs, Airy menyediakan platform online sehingga Anda dapat menelusuri berbagai jenis maskapai penerbangan, akomodasi sementara dan penginapan (sebagaimana berlaku), serta membuat reservasi, pemesanan dan/atau pembelian ("Layanan"). Pengguna dapat membuat pemesanan layanan yang disediakan oleh hotel, maskapai penerbangan, dan/atau penyedia layanan lain yang bekerjasama dengan Airy ("Vendor") di Situs. Dengan meletakkan pesanan melalui Situs, Anda akan dapat memesan dan/atau membeli tiket pesawat, kamar hotel, atau layanan lainnya pada Situs kami. Kami akan memberikan konfirmasi pemesanan atau pembelian melalui konfirmasi email. Kami berhak untuk menolak pemesanan sebagaimana diatur di bawah ini.</span></li>
                    <li><span>Meskipun kami akan menggunakan keahlian kami dengan hati-hati dalam melakukan layanan, kami tidak memverifikasi, dan tidak menjamin, bahwa semua informasi yang diberikan akurat, lengkap, benar atau terbaru yang tersedia, dan kami tidak bertanggung jawab atas setiap kesalahan (termasuk kesalahan penempatan dan pengetikan), gangguan (baik sementara dan/atau parsial, kerusakan, perbaikan atau peningkatan ke situs atau sebaliknya), informasi yang tidak akurat, menyesatkan atau palsu atau informasi yang tidak tersampaikan. Hal ini mencakup setiap informasi yang ditampilkan pada Situs atau platform kami lainnya sehubungan dengan jenis pesawat, tata kursi, jarak antar kursi, serta ketersediaan hiburan di pesawat dan WiFi, atau informasi lainnya yang berkenaan dengan spesifikasi fasilitas penerbangan.</span></li>
                    <li><span>Perubahan dalam kondisi pasar atau keadaan yang terjadi dapat menyebabkan perubahan dalam waktu singkat, yang menyebabkan informasi tidak akurat atau tidak berlaku. Dalam hal terjadi masalah, layanan pelanggan dapat berusaha untuk membantu Anda dan memenuhi permintaan Anda.</span></li>
                    <li><span>Situs ini tidak mengemukakan pernyataan apa pun dan tidak dapat dianggap sebagai membuat rekomendasi atau saran dari tingkat kualitas layanan atau peringkat dari Vendor yang terdaftar di Situs. Dengan ini kami menyatakan penyangkalan klaim, kerugian atau kewajiban sehubungan dengan kualitas atau status Vendor yang ada dan yang terdaftar di Situs (yang memberikan layanan maskapai penerbangan, hotel, atau layanan lainnya). Vendor dapat diperkenalkan dalam tingkatan kelas yang berbeda berdasarkan faktor-faktor termasuk namun tidak terbatas pada ulasan, peringkat mereka atau faktor-faktor lainnya. Peringkat yang diberikan dihitung berdasarkan algoritma otomatis yang dapat diperbarui dan diubah dari waktu ke waktu, sesuai dengan kebijaksanaan tunggal kami.</span></li>
                    <li><span>Kami memiliki hak untuk tidak menerima setiap pengguna atau pemesanan (atau dalam kasus-kasus tertentu membatalkan konfirmasi pemesanan) berdasarkan kebijaksanaan tunggal kami dan untuk alasan apa pun serta tanpa memberikan alasan penolakan/penampikan/pembatalan. Alasan untuk menolak pengguna atau pemesanan atau membatalkan konfirmasi pemesanan dapat termasuk namun tidak terbatas pada: pelanggaran Syarat ini, perdagangan atau sanksi ekonomi oleh otoritas global atau nasional, embargo, larangan dalam peraturan, penipuan atau pencurian (atau indikasi atau dugaan penipuan atau pencurian), dugaan kegiatan kriminal, pemesanan yang mencurigakan, layanan yang tidak tersedia atau tidak lagi disediakan oleh Vendor, pengguna memberikan informasi yang tidak akurat, keliru atau menyesatkan, masalah dengan komunikasi kartu kredit elektronik, informasi atau transaksi, perilaku yang tidak pantas, ancaman, hinaan, penolakan untuk memberikan informasi, hambatan praktis, kesulitan atau kemacetan komunikasi, Kesalahan Nyata (selanjutnya dijelaskan di bawah ini), sejarah pelanggaran Syarat atau penolakan tersebut, atau dimasukkan pada setiap "daftar hitam" atau "daftar pengamatan" oleh pemerintah atau organisasi internasional. Dalam kasus pemesanan ditolak atau dibatalkan oleh Airy dan pembayaran telah dilakukan, Airy akan mengganti jumlah yang telah dibebankan tanpa biaya lebih lanjut. Kami dapat menghilangkan atau menghapus ("Dihapus") keanggotaan pengguna Situs ini sewaktu-waktu, baik sementara atau permanen. Pengguna yang Dihapus dilarang untuk mencoba menggunakan Situs dengan nama lain atau melalui pengguna lainnya (selanjutnya dijelaskan dalam ketentuan Mekanisme Pencegahan Penipuan).</span></li>
                    <li><span>Dalam kasus tertentu, kami dapat membatalkan atau menolak pemesanan berkenaan dengan "Kesalahan Nyata", yang tidak tergantung pada letak kesalahan berasal. Untuk menghindari keraguan, Kesalahan Nyata adalah kesalahan pada Situs (misalnya, dalam hal harga) yang tidak ada satu orang yang rasional pun akan menganggap layak atau membuat bisnis dimengerti. Jumlah yang dibebankan akan diganti tanpa biaya lebih lanjut dalam kasus seperti itu.</span></li>
                </ol>
                <h4><span>PEMBATALAN</span></h4>
                <ol>
                    <li><span>Dengan membuat pemesanan, pesanan atau reservasi melalui Situs, Anda menerima dan setuju dengan syarat dan ketentuan dari Vendor yang berlaku, termasuk yang berkaitan dengan kebijakan tentang pembatalan dan/atau ketiadaan, atau sehubungan dengan permintaan khusus Anda yang mungkin diberikan kepada Vendor. Airy tidak bertanggung jawab atas setiap pelanggaran syarat dan ketentuan yang disepakati antara Vendor dan pengguna, atau yang didasarkan pada permintaan khusus pengguna, sehingga harap membaca syarat dan ketentuan Vendor dengan cermat.</span></li>
                    <li><span>Sehubungan dengan pembatalan pengguna yang telah dilakukan, Airy mungkin dapat menahan atau mengambil bagian dari jumlah yang dibayarkan untuk mengganti biaya yang telah dikeluarkan sehubungan dengan pembatalan.</span></li>
                
                </ol>
                <h4><span>PERMINTAAN KHUSUS</span></h4>
                <ol>
                    <li><span>Dalam hal permintaan khusus sehubungan dengan pemesanan (misalnya: kamar yang mudah diakses dengan kursi roda, bantuan kursi roda untuk penyandang cacat di hotel atau maskapai penerbangan, perubahan nama, perubahan tanggal dan/atau jadwal, menambahkan poin "frequent flyer", kelengkapan khusus yang dibutuhkan dalam perjalanan wisata atau setara), pengguna dapat memasukkan permintaan saat melakukan pemesanan di Situs atau hubungi Vendor secara langsung (sebagaimana berlaku). Permintaan akan diurus berdasarkan kebijaksanaan Vendor dan Airy, berdasar atas ketersediaan dan faktor lainnya. Keberadaan permintaan khusus Anda dapat dikenakan harga dan/atau biaya tambahan oleh Vendor terkait berdasarkan kebijakan dan/atau ketentuan dari masing-masing Vendor. Airy tidak bertanggung jawab atas ketersediaan dan/atau terpenuhinya permintaan khusus Anda oleh Vendor.</span></li>
                    <li><span>Sehubungan dengan perubahan pemesanan (termasuk namun tidak terbatas pada perubahan tanggal, rute dan/atau penumpang) yang dilakukan oleh pengguna, Airy berhak membatalkan pesanan baru yang dibuat melalui proses perubahan pemesanan tersebut, jika pesanan awal sudah tidak berlaku (termasuk namun tidak terbatas, dalam hal apabila tiket telah digunakan atau dikembalikan/refund).</span></li>
                </ol>
                <h4><span>SARAN PERJALANAN</span></h4>
                <ol>
                    <li><span>Dengan menampilkan destinasi tertentu, Airy tidak mengemukakan atau menjamin bahwa perjalanan ke tempat-tempat tersebut bermanfaat atau bebas risiko dan Airy tidak akan dimintai pertanggungjawaban atas kerusakan atau kerugian yang mungkin diakibatkan dari perjalanan ke destinasi tersebut. Dalam situasi apa pun, Airy tidak akan bertanggung jawab atas insiden merugikan yang terjadi selama perjalanan atau selama Anda tinggal. Anda secara pribadi bertanggung jawab untuk pemilihan perjalanan, rute dan destinasi perjalanan, untuk sepanjang perjalanan Anda. Airy tidak bertanggung jawab atas kerugian yang terjadi ketika Anda gagal membawa dokumen perjalanan yang diperlukan, seperti paspor Anda, e-tiket, e-voucher, dan hal-hal lainnya yang disebabkan oleh kesalahan dan/atau kelalaian Anda. Airy juga tidak bertanggung jawab atas segala kesalahan dan/atau kelalaian yang disebabkan oleh Vendor.</span></li>
                    <li><span>Anda bertanggungjawab sepenuhnya untuk mendapatkan, menjaga dan menyediakan untuk ditunjukkan, izin-izin perjalanan atau persyaratan-persyaratan izin masuk orang asing yang sesuai dan sah (termasuk, namun tidak terbatas pada, visa atau izin-izin perjalanan lainnya, baik untuk transit atau keperluan lainnya) yang berlaku untuk Anda sebelum Anda memfinalisasi pengaturan perjalanan Anda sesuai dengan hukum yang berlaku di negara asal, tujuan, lewati atau transit dalam perjalanan Anda. Airy tidak memiliki kewajiban dan tidak akan bertanggungjawab untuk memberitahukan Anda mengenai pengaturan perjalanan dan izin-izin yang dibutuhkan oleh Anda agar dapat melaksanakan rencana perjalanan anda. Airy memiliki haknya untuk membatasi pertanggungjawabannya dalam hal adanya kerugian atau kerusakan yang timbul dari atau sehubungan dengan izin-izin perjalanan Anda.</span></li>
                </ol>
                <h4><span>PERINGKAT</span></h4>
                <ol>
                    <li><span>Peringkat yang ditampilkan di Situs hanya disediakan sebagai informasi dari pengguna saja, dan peringkat yang ada didasarkan pada informasi yang diberikan oleh pihak ketiga seperti pemasok, pengguna atau ulasan situs web lain. Kami tidak memverifikasi peringkat yang diberikan dan karena itu tidak bertanggung jawab atas keakuratan peringkat yang ada. Dengan ini kami menyatakan penyangkalan klaim, kerugian atau kewajiban sehubungan dengan peringkat yang ditampilkan pada Situs.</span></li>
                </ol>
                <h4><span>HARGA DAN PROMOSI</span></h4>
                <ol>
                    <li><span>Kami dapat menawarkan harga yang lebih rendah dan/atau promosi dari waktu ke waktu. Harap diketahui bahwa hal tersebut mungkin memerlukan ketentuan dan persyaratan yang berbeda, misalnya, sehubungan dengan kebijakan pemesanan dan pengembalian dana.</span></li>
                    <li><span>Apabila ada promosi yang diberikan oleh Vendor secara langsung, maka hak dan wewenang atas promosi tersebut sepenuhnya berada pada Vendor dan mungkin tidak berlaku untuk pemesanan yang dilakukan melalui Airy.</span></li>
                </ol>
                <h4><span>BIAYA TAMBAHAN &amp; PENGEMBALIAN DANA</span></h4>
                <ol>
                    <li><span>Setiap harga yang tercantum pada Situs ini hanya tersedia dengan ketentuan tertentu dan harga tersebut dapat berubah tergantung pada ketersediaan pemesanan, lamanya pemesanan dan/atau kuota. Harga yang tersedia dapat mencakup pajak tambahan dan biaya lainnya lagi tapi dalam keadaan tertentu mungkin tidak termasuk pajak dan biaya jasa lainnya (seperti biaya tips untuk pemandu wisata, biaya fasilitas lainnya (jika ada), dan biaya-biaya lainnya yang timbul bukan dari penggunaan layanan kami); pengguna setuju bahwa mereka bertanggung jawab untuk memverifikasi total biaya yang harus dibayar dan persyaratan lainnya dan rincian ketika email konfirmasi dikirim ke pengguna. Pengguna harus memverifikasi pemesanan dalam lembar pemesanan; pengguna dapat membatalkan pemesanan setiap saat sebelum konfirmasi akhir dilakukan. Harga yang ditampilkan terperinci sehingga pengguna dapat melihat jumlah yang harus dibayar, biaya tambahan apa pun yang disebabkan penggunaan kartu kredit atau biaya antar bank yang dikenakan untuk biaya pengiriman akan dibebankan kepada pengguna dan jika terdapat kekurangan dalam jumlah yang dibayarkan, maka Airy dapat memberikan notifikasi email mengenai kekurangan dalam jumlah yang harus dibayarkan pengguna. Dalam hal pengguna membatalkan pemesanan sebelum membayar penuh segala kekurangan yang ada, Airy memiliki kebijaksanaan tunggal apakah akan mengembalikan jumlah yang dibayarkan atau mengembalikan jumlah yang telah dikurangi biaya yang dikeluarkan oleh Airy sebagai akibat dari biaya yang tidak dibayarkan atas kekurangan ini oleh pengguna sesuai dengan prosedur yang ditetapkan oleh Airy. Jika pengguna memiliki keraguan tentang layanan, pengguna dapat menghubungi layanan pelanggan Airy (selama waktu operasional layanan pelanggan yang ditentukan oleh Airy). Untuk setiap pembatalan lainnya, Airy akan bekerja dengan Anda untuk mengembalikan dana yang telah dibayar, setelah dikurangi biaya yang dikeluarkan oleh Airy, misalnya biaya transfer antar bank. Pengembalian dana mungkin tidak segera tergantung pada metode awal pembayaran. Anda dapat menghubungi layanan pelanggan Airy untuk rincian lebih lanjut mengenai perkiraaan durasi untuk menerima pengembalian dana Anda dan kami akan membantu Anda sebaik yang kami mampu.</span></li>
                    <li><span>Airy tidak akan bertanggung jawab atau berkewajiban atas setiap penerbitan e-tiket, e-voucher, atau transaksi lainnya yang digugurkan akibat jumlah yang ditransfer tidak akurat oleh pengguna. Setiap transfer yang dilakukan melebihi batas waktu untuk transfer akan mengakibatkan pemesanan digugurkan. Untuk waktu nyata (real-time) transfer antar bank, Anda harus menggunakan ATM. Setelah menyelesaikan transfer antar bank, harap konfirmasi pembayaran Anda dengan mengisi formulir konfirmasi pembayaran.</span></li>
                </ol>
                <h4><span>BIAYA TAMBAHAN DARI HOTEL</span></h4>
                <ol>
                    <li><span>Harap diketahui bahwa semua harga untuk reservasi kamar yang diberikan melalui Situs kami ("Harga Kamar") berdasarkan pada pilihan Anda, seperti untuk periode tinggal yang diminta dan jumlah tamu, kecuali ditentukan lain. Tarif reservasi kamar dikutip per kamar dan per malam. Anda bertanggung jawab untuk memverifikasi apakah pilihan dan permintaan Anda atau layanan tambahan apa pun tercermin dalam harga yang ditampilkan di Situs (seperti Informasi Kamar disediakan sebelum konfirmasi pemesanan final) dan/atau dalam konfirmasi email kupon. Sarapan umumnya tidak termasuk, kecuali dinyatakan lain. Anda bertanggung jawab untuk memverifikasi setiap penjelasan atau kebijakan yang disediakan oleh hotel di Situs. Asuransi apa pun tidak termasuk dalam harga, kecuali dinyatakan lain. Standar reservasi kamar hotel adalah untuk satu hingga dua tamu; biaya tambahan umumnya akan diperlukan untuk tempat tidur tambahan. Hotel dapat menolak untuk menerima tamu tambahan jika tidak diberitahukan sebelumnya.</span></li>
                    <li><span>Harap diketahui bahwa beberapa hotel dapat membebani Anda biaya resor, tetapi mungkin memerlukan beban tambahan (atau sejenisnya) untuk menggunakan layanan tertentu. Biaya resor umumnya tidak termasuk dalam Harga Kamar; detail selengkapnya akan dicantumkan dalam deskripsi kamar di Situs. Anda mungkin juga akan dibebankan secara langsung oleh hotel untuk produk dan layanan termasuk namun tidak terbatas pada: biaya tambahan energi, biaya penanganan bagasi, biaya pengiriman surat kabar, biaya keamanan dalam kamar, biaya perjalanan/wisata, atau biaya untuk membersihkan kamar. Praktik menambahkan beban hotel tambahan berada di luar kendali Airy.</span></li>
                    <li><span>Pengeluaran insidental opsional dan beban pemakaian pribadi (seperti yang dikeluarkan selama tinggal di Hotel / Penginapan) umumnya tidak termasuk dalam Harga Kamar. Beban tersebut termasuk namun tidak terbatas pada: biaya parkir, biaya minibar di dalam kamar, biaya telepon, layanan kamar, biaya makanan dan minuman, biaya makan malam (gala) khusus, sewa film/film sesuai permintaan (on-demand), dan biaya penggunaan Internet. Selama puncak musim liburan tertentu, beberapa hotel mungkin membuat makan malam spesial yang diwajibkan (seperti untuk Tahun Baru, Natal, Tahun Baru Cina dan acara lainnya). Beban tersebut tidak termasuk dalam tarif kamar, tapi akan ditampilkan pada formulir pemesanan. Harap merujuk ke detail selanjutnya yang tertera di bawah "Informasi Penting", "Persyaratan Pemesanan", "Kebijakan Pembatalan" atau judul serupa di Situs. Jika Anda tidak yakin apakah ada atau tidak ada beban yang dimasukkan dalam tarif, harap hubungi tim layanan pelanggan kami untuk mengklarifikasi.</span></li>
                    <li><span>Beberapa hotel tertentu dapat menambahkan biaya untuk transportasi atau perpindahan. Hal ini merupakan praktik yang jamak untuk bepergian antar pulau, agar supaya mencapai hotel. Transportasi tersebut selalu diatur oleh hotel, dan ditawarkan oleh atau atas nama hotel, yang bertanggung jawab terhadap layanan transportasi. Anda setuju bahwa Airy tidak mengatur transportasi apa pun dan tidak bertanggung jawab untuk layanan transportasi tersebut. Anda menyetujui bahwa Airy tidak bertanggung jawab atas kualitas, keselamatan, frekuensi atau tingkat layanan jasa transportasi, dan terhadap setiap kerugian atau kerusakan yang mungkin diakibatkan dari penggunaan layanan transportasi tersebut.</span></li>
                    <li><span>Dalam beberapa yurisdiksi, hotel mungkin diwajibkan untuk memungut pajak hunian atau pajak kota setempat dari tamu secara langsung. Otoritas pemerintah juga dapat menyatakan pajak tambahan dan dapat mewajibkan hotel untuk memungut pajak tersebut secara langsung. Anda setuju untuk membayar setiap dan semua pajak/beban ke hotel secara langsung setelah keluar hotel (checkout), kecuali ditentukan lain. Ketika Anda tidak yakin, harap cek dengan hotel atau Layanan Pelanggan Airy mengenai biaya tambahan apa pun yang mungkin dicantumkan dalam Harga Hotel.</span></li>
                </ol>
                <h4><span>DETAIL DAN PROSEDUR PEMBAYARAN</span></h4>
                <ol>
                    <li><span>Pembayaran dilakukan dalam jumlah dan mata uang sebagaimana dinyatakan tanpa biaya bank penjamin atau beban lain apa pun oleh Airy.</span></li>
                    <li><span>Airy tidak memungut pajak atau retribusi. Pembebanan pajak apa pun akan ditanggung oleh pengguna.</span></li>
                    <li><span>Untuk semua bentuk reservasi, Anda harus melakukan pembayaran sebelum batas waktu yang telah ditentukan. Jika pembayaran tidak dilakukan, maka Airy berhak untuk membatalkan semua reservasi atau mengabaikan proses pemesanan.</span></li>
                    <li><span>Metode pembayaran termasuk namun tidak terbatas pada transfer bank dan kartu kredit. Untuk pembayaran melalui transfer bank, Anda harus memberikan tanda terima transfer bank sebagai bukti pembayaran reservasi yang tercantum dalam email konfirmasi Airy. Anda harus mengikuti prosedur yang terdapat dalam email konfirmasi.</span></li>
                    <li><span>Untuk metode pembayaran lainnya seperti kartu kredit, Anda harus mengikuti prosedur yang dinyatakan oleh Airy dan/atau penyedia layanan pembayaran terkait.</span></li>
                    <li><span>Setelah Anda melakukan pembayaran penuh, Airy akan menempatkan pesanan dan mengeluarkan kode reservasi, yang akan disertai dengan:</span></li>
                <ol>
                <h4><span>PEMBAYARAN DENGAN KARTU KREDIT &amp; PENIPUAN</span></h4>
                <ol>
                    <li><span>Untuk pembayaran pemesanan yang ditempatkan melalui Situs ini, kartu kredit Anda akan ditagih oleh Airy untuk harga penuh pada saat pemesanan dan konfirmasi dari pemesanan (setiap pengembalian yang mungkin diberikan akan tergantung pada ketentuan reservasi yang ada). Anda harus memeriksa rincian pemesanan secara menyeluruh setiap saat sebelum Anda membuat reservasi. Airy akan memproses setiap pengembalian, sebagaimana berlaku, dalam jangka waktu yang wajar. Untuk reservasi tertentu, Airy mungkin tidak membebani kartu kredit Anda dan meminta pembayaran kepada Vendor terkait secara langsung dan tidak membebani kartu kredit Anda, karena Anda wajib membayar vendor terkait secara langsung. Dalam rangka menjaga dan mengenkripsi informasi kartu kredit Anda ketika transit pada kami, kami menggunakan teknologi enkripsi seperti Transport Layer Security ("TLS") atau Secure Sockets Layer ("SSL") untuk layanan kami.</span></li>
                    <li><span>Dalam hal adanya penipuan kartu kredit atau penyalahgunaan atas kartu kredit anda oleh pihak ketiga, anda harus segera menghubungi bank atau penerbit kartu anda setelah anda mengetahui adanya penyalahgunaan tersebut. Dalam hal ini, Airy tidak akan bertanggungjawab atas setiap kejadian penipuan kartu kredit atau penyalahgunaan atas kartu kredit anda oleh pihak ketiga, tanpa mengesampingkan apakah kejadian penipuan atau penyalahgunaan tersebut dilakukan melalui jasa Airy. Airy tidak berkewajiban untuk melakukan pengembalian pembayaran atau membayarkan kembali kepada anda sebagai akibat dari penipuan tersebut. Sebagai bagian dari itikad baik kami, kami dapat memberikan suatu bentuk kompensasi kepada anda berdasarkan kepada peninjauan dan persetujuan dari kami. Anda hanya akan berhak untuk meminta kompensasi apabila pemesanan tersebut dilakukan melalui server aman kami dan penipuan atau penyalahgunaan atas kartu kredit anda merupakan akibat dari kesalahan atau kelalaian kami dan bukan akibat dari kesalahan anda sendiri ketika menggunakan server aman kami. Kami tidak bertanggungjawab atas penipuan atau penyalahgunaan atas kartu kredit anda apabila hal tersebut dilakukan melalui aplikasi atau server selain milik kami atau apabila hal tersebut merupakan akibat dari kesalahan atau kelalaian anda sendiri. Apabila anda mencurigai adanya pemesanan tidak sah atau penipuan yang dilakukan pada Airy, anda harus segera menghubungi tim Customer Service kami.</span></li>
                    <li><span>Untuk membuat reservasi, Anda harus berusia di atas delapan belas (18) tahun dan memiliki kapasitas hukum penuh untuk membuat transaksi (atau memiliki wewenang dari wali sah Anda). Anda harus menggunakan kartu kredit atau kartu debit yang Anda miliki, diterbitkan dengan nama Anda, dan pastikan bahwa ada dana yang memadai untuk menutupi biaya transaksi. Anda menerima tanggung jawab keuangan untuk semua transaksi yang dilakukan atas nama Anda atau akun Anda.</span></li>
                    <li><span>Anda harus memastikan bahwa rincian yang Anda berikan kepada kami adalah sepenuhnya benar, tepat dan akurat. Airy berhak untuk tidak menerima kartu kredit tertentu. Airy dapat menambah atau menghapus metode pembayaran lainnya atas kebijaksanaannya.</span></li>
                    <li><span>Dalam kasus tertentu, kami mungkin memerlukan informasi tambahan atau verifikasi untuk memvalidasi dan mengkonfirmasi pemesanan, seperti yang dijelaskan secara lebih rinci dalam Situs. Pemesanan tidak dikonfirmasi sampai Anda telah menerima email konfirmasi dengan e-tiket atau voucer dan terdapat kemungkinan bahwa Vendor dapat menerapkan mekanisme pemeriksaan penipuan selama proses pemesanan. Jika terjadi penipuan atau ditentukan akan terjadi, maka pemesanan tidak akan lagi tersedia atau secara otomatis menjadi tidak berlaku. Airy tidak akan memikul tanggung jawab apa pun. Jika Anda memilih untuk tidak mengirimkan informasi tambahan, reservasi tidak akan diselesaikan dan akan menjadi tidak berlaku.</span></li>
                </ol>
                <h4><span>HAK DAN KEWAJIBAN</span></h4>
                <ol>
                    <li><span>Airy dengan ini memberikan pengguna hak terbatas tertentu (merupakan "Lisensi Terbatas"), yang tidak dapat dipindahkan atau didelegasikan, untuk mengakses dan menggunakan Situs sejauh mana dinyatakan diizinkan oleh Syarat ini. Sehubungan dengan Lisensi Terbatas ini, kami tidak akan memberikan Anda hak atau lisensi sehubungan dengan penggunaan Situs; hak atau lisensi yang tidak diberikan secara tersurat, sepenuhnya dimiliki oleh Airy atau pemilik pihak ketiga lainnya dari lisensi tersebut. Konten yang tersedia di Situs (termasuk infrastruktur perangkat lunak yang digunakan untuk menyediakan Konten) sepenuhnya dimiliki oleh Airy atau pemasok dan penyedia layanannya, termasuk namun tidak terbatas pada Vendornya (sebagaimana berlaku). Anda dapat menggunakan situs tersebut untuk menaruh pesanan dan Anda dengan ini menyatakan dan menjamin bahwa Anda tidak akan mengajukan permintaan reservasi palsu atau spekulatif untuk mengantisipasi pemesanan yang tersedia. Anda dengan ini menyatakan untuk memastikan bahwa informasi pembayaran yang Anda berikan adalah benar dan sepenuhnya akurat. Anda juga menjamin untuk memberikan alamat surat elektronik yang tepat dan akurat, alamat surat menyurat dan/atau rincian informasi kontak Anda.</span></li>
                    <li><span>Berkaitan dengan Syarat Penggunaan dari Situs, Anda setuju untuk tidak menggunakan Situs atau Konten untuk tujuan komersial atau baik secara langsung maupun tidak langsung untuk tujuan selain penggunaan pribadi atau untuk yang melanggar hukum (dilarang oleh hukum) atau melakukan tindakan yang melanggar Syarat tersebut. Kecuali dengan kesepakatan tertulis dari Airy, Anda setuju untuk tidak memodifikasi, menyalin, mendistribusikan, mengirimkan, menampilkan, mereproduksi, mempublikasikan, melisensikan, menciptakan karya turunan dari, mentransfer, atau menjual atau menjual kembali setiap informasi, perangkat lunak, produk atau layanan yang diperoleh sehubungan dengan Situs. Selain itu, Anda setuju untuk tidak:</span></li>
                    <ol>
                        <li><span>menggunakan Situs ini atau Konten untuk tujuan komersial tanpa izin dari Airy;</span></li>
                        <li><span>mengakses, memonitor atau menyalin Konten pada Situs menggunakan teknologi, perangkat lunak, atau program apa pun baik secara manual atau otomatis untuk tujuan apa pun tanpa izin tertulis dari Airy;</span></li>
                        <li><span>melakukan tindakan apa pun yang membebani atau mungkin membebani, tanggungan yang tidak wajar pada Situs atau infrastruktur kami;</span></li>
                        <li><span>membuat tautan utama ke Situs ini (termasuk namun tidak terbatas pada jalur pemesanan) untuk tujuan apa pun tanpa persetujuan tertulis dari Airy;</span></li>
                        <li><span>menjual kembali, menggunakan, menyalin, melakukan pengawasan (seperti menggunakan atau memasang program spider atau scrape), menampilkan, mengunduh atau melakukan produksi Konten apa pun, perangkat lunak, produk, layanan yang tersedia melalui Situs untuk tujuan komersial atau tujuan/kegiatan kompetisi;</span></li>
                        <li><span>mereproduksi Situs (melalui "frame" atau "mirror") atau mengatur bagian dari Situs ini pada setiap situs web lain tanpa persetujuan tertulis sebelumnya;</span></li>
                        <li><span>mengirim pengumuman ke atau melalui Situs yang melanggar hukum, peraturan, atau aturan, atau yang dapat mendukung kegiatan yang melanggar hukum atau kegiatan kriminal;</span></li>
                        <li><span>mengirimkan atau menyediakan tautan ke atau mengirimkan pengumuman yang mengandung materi yang dapat dianggap berbahaya, cabul, pornografi, tidak senonoh, kekerasan, rasis, atau merupakan diskriminasi, hinaan, ancaman, pelecehan, penindasan, kebencian atau materi tidak menyenangkan lainnya, sesuai dengan kebijaksanaan Airy ini;</span></li>
                        <li><span>mengirimkan atau menyediakan tautan ke setiap pengumuman yang mengandung bahasa pencemaran nama baik, fitnah, dan kebohongan;</span></li>
                        <li><span>mengirimkan atau melakukan pengumuman yang mungkin melanggar kekayaan intelektual atau hak-hak lain dari entitas atau orang tertentu, termasuk namun tidak terbatas pada hak cipta, paten, merek dagang, rahasia dagang atau informasi rahasia atau publikasi;</span></li>
                        <li><span>mengirimkan pengumuman ketika dilarang oleh hukum yang berlaku atau melanggar hak dan kewajiban yang ada berdasarkan hubungan kontraktual;</span></li>
                        <li><span>meniru orang atau kelompok apa pun, atau menyatakan dengan keliru atau salah mengemukakan kepada seseorang atau entitas terhadap hubungan atau mengambil identitas palsu jika tujuannya untuk menyesatkan, menipu atau memperdaya;</span></li>
                        <li><span>memanipulasi atau memalsukan informasi yang bertujuan untuk menyamarkan asal-usul pernyataan yang Anda berikan;</span></li>
                        <li><span>menggunakan Situs dengan cara apa pun yang dapat merusak, menonaktifkan, menghambat, atau mengganggu penggunaan Situs atau pengguna lain dari peralatan komputer, atau menyebabkan kerusakan, gangguan atau membatasi fungsi dari perangkat lunak, perangkat keras atau peralatan telekomunikasi;</span></li>
                        <li><span>mendapatkan akses tidak sah atau melakukan modifikasi yang tidak sah ke Situs atau situs web terkait lainnya, akun lainnya, sistem komputer, jaringan yang terhubung dengan Situs dengan cara meretas, pencurian kata sandi atau hal-hal lain yang sejenis;</span></li>
                        <li><span>memperoleh atau berusaha memperoleh materi atau informasi apa pun dengan cara yang tidak sengaja disediakan oleh situs (termasuk namun tidak terbatas pada destinasi lain yang disediakan oleh situs ini). Hal ini termasuk namun tidak terbatas pada, memperoleh atau mengumpulkan informasi tentang orang lain seperti alamat email;</span></li>
                        <li><span>terlibat dalam tindakan penipuan atau tindakan yang bertujuan untuk memanipulasi halaman hasil mesin pencari ("SERP") atau melakukan optimasi mesin pencari ("SEO"). Praktik SEO dianggap tidak etis atau merupakan "spamdexing" termasuk namun tidak terbatas pada cloaking, metadata, tag judul, scraping konten, skema tautan, google bomb, pencarian kata kunci, teks tersembunyi atau tautan tersembunyi, skema tautan, komentar yang mengandung spam dan hal-hal lain; atau</span></li>
                        <li><span>tindakan lain apa pun yang dapat memberi pengaruh negatif atau mengakibatkan kerusakan pada Situs, Airy atau afiliasinya dan karyawan, atau reputasi Airy ini.</span></li>
                    </ol>
                    <li><span>Kecuali ditentukan lain secara tegas, situs web tidak diizinkan untuk membuat tautan ke halaman lain selain halaman utama Situs atau frame atau halaman web atau materi yang terkandung di dalamnya, atau membuat tautan ke aspek Situs dalam bentuk email dengan tujuan komersial tanpa persetujuan tertulis yang dinyatakan oleh Airy.</span></li>
                    <li><span>Dengan menempatkan pesanan melalui Situs ini, Anda dengan ini menyatakan dan menjamin bahwa Anda tidak dikenakan larangan atau pembatasan apa pun oleh program sanksi apa pun, atau dikenakan hukuman di bawah rezim antipencucian uang mana pun.</span></li>
                </ol>
                <h4><span>HAK UNTUK KONTEN PENGGUNA</span></h4>
                <ol>
                    <li><span>Dengan menyelesaikan pemesanan, Anda dengan ini setuju untuk menerima surat elektronik yang berisi undangan untuk memberikan ulasan atau ulasan konten terkait dengan pemilihan Vendor. Airy memiliki kebijaksanaan tunggal apakah korespondensi Anda akan muncul dalam ulasan. Airy dapat menampilkan korespondensi, yang mungkin berisi komentar, tingkat layanan dan nama Anda.</span></li>
                    <li><span>Dalam memberikan ulasan, Anda setuju untuk memastikan bahwa:</span></li>
                    <ol>
                        <li><span>Anda memiliki dan mengendalikan semua hak atas ulasan yang Anda berikan ke Situs;</span></li>
                        <li><span>konten ulasan akurat dan tidak mengandung penggambaran yang keliru; dan</span></li>
                        <li><span>penggunaan atau kinerja atau pengiriman konten ulasan tidak melanggar Syarat atau undang-undang dan peraturan yang berlaku, Anda tidak melanggar hak pihak ketiga, dan Anda tidak menyebabkan cedera pada pihak mana pun.</span></li>
                    </ol>
                    <li><span>Anda harus memikul semua tanggung jawab atas</span></li>
                </ol>
            </div>
        </div>
    </div>
</div>
@endsection